restPort: 8091

modelProvider:
  type: diskProvider
  baseDir: "./model_repo"

modelCache:
  hostModelPath: "./models"
  size: 30000

serving:
  servingModelPath: "/models"
  grpcHost: "localhost:8500"
  restHost: "http://localhost:8501"

serviceDiscovery:
  type: consul
  serviceName: tfservingcache
  serviceId: foo1
  heartbeatTTL: 5
