proxyRestPort: 8091
cacheRestPort: 8092

modelProvider:
  type: diskProvider
  baseDir: "./model_repo"

modelCache:
  hostModelPath: "./models"
  size: 30000

serving:
  servingModelPath: "/models"
  grpcHost: "localhost:8500"
  restHost: "http://localhost:8501"
  maxConcurrentModels: 2

proxy:
  replicasPerModel: 3

serviceDiscovery:
  #### CONSUL ####
  #type: consul
  #serviceName: tfservingcache
  #serviceId: foo1
  #heartbeatTTL: 5
  #### ETCD ####
  type: etcd
  serviceName: tfservingcache
  heartbeatTTL: 5
  endpoints: ["localhost:2379"]
  authorization:
    username: root
    password: foobar
