proxyRestPort: 8093
proxyGrpcPort: 8100
cacheRestPort: 8094
cacheGrpcPort: 8095

metrics:
  metricsPath: "/monitoring/prometheus/metrics"

modelProvider:
  type: diskProvider
  baseDir: "./model_repo"
#modelProvider:
#  type: s3Provider
#  s3:
#    bucket: foo
#    basePath: models/foo/bar

modelCache:
  hostModelPath: "./models"
  size: 30000

serving:
  servingModelPath: "/models"
  grpcHost: "localhost:8500"
  restHost: "http://localhost:8501"
  maxConcurrentModels: 2
  grpcConfigTimeout: 10 # timeout in seconds
  grpcPredictTimeout: 60
  metricsPath: "/monitoring/prometheus/metrics"

proxy:
  replicasPerModel: 3
  grpcTimeout: 10

serviceDiscovery:
  allowLocalhost: true
  #### CONSUL ####
  #type: consul
  #serviceName: tfservingcache
  #serviceId: foo1
  #heartbeatTTL: 5
  #### ETCD ####
  type: etcd
  serviceName: tfservingcache
  heartbeatTTL: 5
  endpoints: ["localhost:2379"]
  authorization:
    username: root
    password: foobar
